### ISSUE TITLE
Create a README.md file

### ISSUE THREAD

**Issue by smsunarto** [Terasology/Lost#1]
The README file should include:

1. Screenshot of the gameplay (Ideally no spoilers)
2. Brief description of the gameplay
3. Estimated play time, difficulty, genre, etc

Feel free to add anything that you think necessary.

CC: @nihal111 @Cervator

**Comment by ThanoshanMV** [comment]
Hi, how to run this application ?

**Comment by jdrueckert** [comment]
Hi @ThanoshanMV, please note that `Lost` is only one of Terasology's many modules and one of ~10 gameplays  (basically module collections).
For the basic dev setup and instructions how to start please check our main Terasology wiki: https://github.com/MovingBlocks/Terasology/wiki/Dev-Setup

**Comment by 4Denthusiast** [comment]
Resolved by #23.
